{{- if and .Values.certificate.enabled .Values.ingress.enabled .Values.ingress.tls }}
{{- $root := . }}
{{- range .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "iron-dome-simulator.labels" $root | nindent 4 }}
spec:
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ index $root.Values.ingress.annotations "cert-manager.io/cluster-issuer" | default "letsencrypt-prod" }}
  secretName: {{ .secretName }}
  usages:
    - digital signature
    - key encipherment
---
{{- end }}
{{- end }}