# Default values for iron-dome-simulator
replicaCount: 1

image:
  repository: ghcr.io/roeej/irondome
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is "latest"
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080  # High port for non-root nginx

ingress:
  enabled: false
  className: "traefik"
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: iron-dome.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: iron-dome-tls
  #    hosts:
  #      - iron-dome.example.com

# Certificate generation (optional, only if cert-manager is not handling it via ingress annotations)
certificate:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Additional environment variables
env: []
  # - name: EXAMPLE_VAR
  #   value: "example-value"

# Health check configuration
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Nginx configuration
nginx:
  workerProcesses: "auto"
  workerConnections: 1024
  keepaliveTimeout: 65

# Volume mounts for nginx cache and temp files
volumeMounts:
  - name: cache
    mountPath: /var/cache/nginx
  - name: tmp
    mountPath: /tmp
  - name: var-log
    mountPath: /var/log/nginx

volumes:
  - name: cache
    emptyDir: {}
  - name: tmp
    emptyDir: {}
  - name: var-log
    emptyDir: {}