// Battery Tube Configuration
// Generated by Tube Position Editor
// 2025-06-27T02:10:05.138Z

import * as THREE from 'three';

export interface TubeConfig {
  id: number;
  start: { x: number; y: number; z: number };
  end: { x: number; y: number; z: number };
  direction: { x: number; y: number; z: number };
}

export const BATTERY_TUBE_CONFIG: TubeConfig[] = [
  {
    id: 0,
    start: { x: -2.926, y: 11.236, z: 1.681 },
    end: { x: -6.641, y: 4.994, z: 0.269 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 1,
    start: { x: -2.600, y: 11.274, z: 0.618 },
    end: { x: -6.316, y: 5.032, z: -0.794 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 2,
    start: { x: -2.275, y: 11.312, z: -0.445 },
    end: { x: -5.990, y: 5.070, z: -1.856 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 3,
    start: { x: -1.949, y: 11.350, z: -1.507 },
    end: { x: -5.665, y: 5.108, z: -2.919 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 4,
    start: { x: -1.624, y: 11.388, z: -2.570 },
    end: { x: -5.339, y: 5.146, z: -3.982 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 5,
    start: { x: -2.086, y: 10.681, z: 1.920 },
    end: { x: -5.802, y: 4.439, z: 0.508 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 6,
    start: { x: -1.761, y: 10.719, z: 0.857 },
    end: { x: -5.476, y: 4.477, z: -0.555 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 7,
    start: { x: -1.435, y: 10.757, z: -0.206 },
    end: { x: -5.151, y: 4.515, z: -1.617 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 8,
    start: { x: -1.110, y: 10.795, z: -1.268 },
    end: { x: -4.825, y: 4.553, z: -2.680 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 9,
    start: { x: -0.784, y: 10.833, z: -2.331 },
    end: { x: -4.500, y: 4.591, z: -3.743 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 10,
    start: { x: -1.247, y: 10.126, z: 2.159 },
    end: { x: -4.962, y: 3.884, z: 0.747 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 11,
    start: { x: -0.921, y: 10.164, z: 1.096 },
    end: { x: -4.637, y: 3.922, z: -0.316 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 12,
    start: { x: -0.596, y: 10.202, z: 0.033 },
    end: { x: -4.311, y: 3.960, z: -1.378 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 13,
    start: { x: -0.270, y: 10.240, z: -1.029 },
    end: { x: -3.986, y: 3.998, z: -2.441 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 14,
    start: { x: 0.055, y: 10.278, z: -2.092 },
    end: { x: -3.660, y: 4.036, z: -3.504 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 15,
    start: { x: -0.407, y: 9.570, z: 2.398 },
    end: { x: -4.123, y: 3.328, z: 0.986 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 16,
    start: { x: -0.082, y: 9.608, z: 1.335 },
    end: { x: -3.797, y: 3.366, z: -0.077 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 17,
    start: { x: 0.244, y: 9.647, z: 0.272 },
    end: { x: -3.472, y: 3.405, z: -1.139 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 18,
    start: { x: 0.569, y: 9.685, z: -0.790 },
    end: { x: -3.146, y: 3.443, z: -2.202 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  },
  {
    id: 19,
    start: { x: 0.895, y: 9.723, z: -1.853 },
    end: { x: -2.821, y: 3.481, z: -3.265 },
    direction: { x: -0.502, y: -0.844, z: -0.191 }
  }
];

// Helper function to convert config to Three.js vectors
export function getTubeVectors(tubeId: number): {
  start: THREE.Vector3;
  end: THREE.Vector3;
  direction: THREE.Vector3;
} | null {
  const config = BATTERY_TUBE_CONFIG.find(t => t.id === tubeId);
  if (!config) return null;
  
  return {
    start: new THREE.Vector3(config.start.x, config.start.y, config.start.z),
    end: new THREE.Vector3(config.end.x, config.end.y, config.end.z),
    direction: new THREE.Vector3(config.direction.x, config.direction.y, config.direction.z)
  };
}
