apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iron-dome-simulator-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/roeej/irondome  # Update with your repo URL
    targetRevision: main  # Or use specific tags like v1.0.0
    path: helm/iron-dome-simulator
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: ingress.hosts[0].host
          value: iron-dome.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: iron-dome-prod
  syncPolicy:
    automated:
      prune: false  # Manual approval for production
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10